#! /bin/sh

if [ -z "$1" -o -n "$2" ]; then
   echo "Usage: $0 new_tag" >&2
   exit 1
else
   tag="$1"
fi

`git var GIT_EDITOR` ANNOUNCE ChangeLog setup.cfg setup.py &&
exec git commit --message="Release $tag" ANNOUNCE ChangeLog setup.cfg setup.py
